### ISSUE TITLE
Mark zero pressure samples in both spatial and selected views with different colour

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#88] opened 2015-11-11 11:27 UTC
...because at the moment you can tell the difference between inking and non-inking samples. This is already done in the Time Line.

**Comment by isolver** [comment] 2015-11-11 14:03
This is already in the code, but the issue is that the difference between the two colors is not salient enough. Right now one color is an autogenerated  'darker' version of the other.

I think we should add settings in the prefs dialog so a user can select the colors to use for both inking and non-inking samples. That way there is total control over this by the user.

Is this OK?

**Comment by Mark-Torrance** [comment] 2015-11-11 14:04
Yes. Good.

**Comment by isolver** [comment] 2016-01-22 15:26
closing, fixed in another issue

**Closed as completed by isolver** 2016-01-22 15:26 UTC
Labels: enhancement, Priority 2, MarkWrite
