### ISSUE TITLE
Timeline: selection end not visible when Trial level segment selected

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#142] opened 2016-01-28 13:13 UTC
i.e. when you open a file or select a trial-level segment, and so the selection fills the whole timeline, the right hand yellow line doesn't appear. Can be brought back into range with arrow keys, but not ideal.

**Comment by isolver** [comment] 2016-01-28 13:44
On Thu, Jan 28, 2016 at 8:13 AM, Mark Torrance notifications@github.com
wrote:

> Can be brought back into range with arrow keys, but not ideal.

Agreed it is not ideal. The issue is with the pyqtgraph library, without a
lot of digging I do not think I can fix this without also reintroducing the
bug where both edges of the selection region were not within the timeline
view and could therefore not be moved. Note that although the right edge is
not visible, you can still select and move it with the mouse: press the
mouse just to the left of the end of the selection region, then drag as you
would and the right edge of the region will drag in with the mouse.

Since this is mainly an issue when selecting a trial segment, because the
data bounds are locked to the trials start : end time, perhaps when a trial
node is selected the full trial should not be selected anyhow. Instead the
first run within the trial could be selected.

Ideally, the app could remember where the selection region was when the
user last worked on each trial, and when a trial is reselected, the
selected region could be set to where the user left it for that trial. This
would probably aid in work flow speed. This info could also be saved with
the project data, so when a user saved and reopened a markwrite project,
when a trial is selected in the tree, the initial selection region would be
where it was when the project as saved. However it would take a couple
hours to implement correctly I think.

**Comment by Mark-Torrance** [comment] 2016-01-28 13:49
> Since this is mainly an issue when selecting a trial segment, because the data bounds are locked to the trials start : end time, perhaps when a trial node is selected the full trial should not be selected anyhow. Instead the first run within the trial could be selected.

If trial selection give (a) zoom timeline to range of that trial (current behaviour) and (b) first run is selected that would not only solve the problem but be better.

The "remember where you were thing" would be cool, but not a priority now. We should start a Phase 3 wishlist.

**Comment by isolver** [comment] 2016-01-28 14:05
> If trial selection give (a) zoom timeline to range of that trial (current behaviour) and (b) first run is selected that would not only solve the problem but be better.

Will look into this

> The "remember where you were thing" would be cool, but not a priority now. We should start a Phase 3 wishlist.

Agreed. I'll create a phase 3 milestone and issues that want to be binned for phase 3 can use that.

I never created a phase 2 milestone now that I think of it. I'll do that as well for completeness sake.

**Comment by isolver** [comment] 2016-01-28 15:13
Added phase 2 milestone. Good idea to just use the Future functionality milestone for anything phase 3 or whatever.

Closing this issue and creating one specific for change requested.

**Closed as completed by isolver** 2016-01-28 15:13 UTC
Labels: bug, Priority 1, MarkWrite
